[WUXC_VERSION_RS5]
[webhosthidden]
enum TabViewWidthMode
{
    SizeToContent = 0,
    Fixed = 1,
};

[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TabView : Windows.UI.Xaml.Controls.ListView
{
    TabView();

    [MUX_DEFAULT_VALUE("winrt::TabViewWidthMode::SizeToContent")]
    TabViewWidthMode TabWidthMode{ get; set; };

    static Windows.UI.Xaml.DependencyProperty TabWidthModeProperty{ get; };
}

[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TabViewItem : Windows.UI.Xaml.Controls.ListViewItem
{
    TabViewItem();

    String Header{ get; set; };

    Windows.UI.Xaml.DataTemplate HeaderTemplate{ get; set; };

    Windows.UI.Xaml.Controls.IconElement Icon{ get; set; };

    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HeaderTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IconProperty{ get; };
}
